### ISSUE TITLE
Server Side REST in Context does not work on Sandbox

### ISSUE THREAD

**Issue by hierostratos** [paypal/paypal-checkout-demo#13]
when I click the button in context pops up briefly but closes immediately.
tried Firefox and Chrome
works in live

inContext works in other places so it seems related to the demopage

**Comment by bluepnume** [comment]
@vishakha94 could you take a look? Thanks!

**Comment by bluepnume** [comment]
Are you still seeing this issue?

**Comment by hierostratos** [comment]
seems to be working now.

Thanks
