### ISSUE TITLE
Change to id from paymentID

### ISSUE THREAD

**Issue by trainerbill** [paypal/paypal-checkout-demo#14]
we should have the server just respond with the entire payment object and change the client side to return res.id in the payment callbacks.  I think it will cause less confusion.

![image](https://user-images.githubusercontent.com/3578259/30974699-de4daf2a-a435-11e7-9c04-a1d6a871923d.png)

**Comment by trainerbill** [comment]
Maybe add a couple comments as well.

![image](https://user-images.githubusercontent.com/3578259/30974975-a1e9791e-a436-11e7-876b-60ca42cbe2f0.png)

**Comment by bluepnume** [comment]
Yeah, good plan. 👍
