### ISSUE TITLE
How to retrieve payment id on client side before transaction is executed?

### ISSUE THREAD

**Issue by herbertmilhomme** [paypal/paypal-checkout-demo#15]
Commented inside code. 
I've attempted both `.then()` and even used the param from the function `data` and `actions` neither return a value. I'm assuming the call needs to be made AFTER the payment is created. But "how?" when the transaction is being created on a `return` script.

```html
<script>
/*
    // Render the PayPal button

    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // Specify the style of the button

        style: {
            label: 'checkout',
            size:  'small',    // small | medium | large | responsive
            shape: 'pill',     // pill | rect
            color: 'gold'      // gold | blue | silver | black
        },

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
            production: '<insert production client id>'
        },*/

        payment: function(data, actions) { 
            return actions.payment.create({ //<- specifically over here
                payment: {
                    transactions: [
                        {
                            amount: { total: '0.01', currency: 'USD' }
                        }
                    ]
                }
            }).then(function(payment){
                window.alert(payment.id);  // i desire the payment id. but it keeps returning undefined no matter what i do.
            });
        },
/*
        onAuthorize: function(data, actions) {
            return actions.payment.execute().then(function() {
                window.alert('Payment Complete!');
            });
        }

    }, '#paypal-button-container');
*/
</script>
```

**Comment by bluepnume** [comment]
Hi @herbertmilhomme -- did you find a solution for this? For future readers, you can access `data.paymentID` in `onAuthorize`.

**Comment by herbertmilhomme** [comment]
Yes, thank you. I saw a second js script that had a sample script that worked out perfectly for my needs. It did as you mentioned above and pulled the value from the `onAuth` section/function. 

i ran a check-if, and execute back-to-back in the `onAuth`, which did the same job as if it logically were placed in a flow order earlier in the code process.

**Comment by navaic** [comment]
> Hi @herbertmilhomme -- did you find a solution for this? For future readers, you can access `data.paymentID` in `onAuthorize`.

This was exactly what I needed, couldn't find it in any documentation from paypal and took too many  searches.
