### ISSUE TITLE
Server-Side REST throwing 'Transaction in Invalid' error in production mode

### ISSUE THREAD

**Issue by PP-MTS-Silk** [paypal/paypal-checkout-demo#16]
The server-side REST demo on https://developer.paypal.com/demo/checkout/#/pattern/server is throwing an error in the in-context window of 'Transaction is Invalid. Here is the image. Also the url fallback is https://www.paypal.com/webapps/hermes/fallback?product=ec&fallback=1&token=PAY-2RG33944AJ083411YLIQFA4A

![image](https://user-images.githubusercontent.com/34139466/33448471-c1eed0f8-d5cb-11e7-9787-889b509e992a.png)

We also have a merchant reporting the exact same issue.

**Comment by mstuart** [comment]
Hi @PP-MTS-Silk, this repo is becoming more active now, so we're cleaning up old issues and PRs. I see this issue is from 2017. If this is still happening, please re-open this!
