### ISSUE TITLE
Incorrect JSON format here. 

### ISSUE THREAD

**Issue by shrikkant** [paypal/paypal-checkout-demo#18]
https://github.com/paypal/paypal-checkout-demo/blob/3c42375c2b4692c098df0b0581fb14f6261e8d5b/src/app/server/routes.js#L45

Shouldn't this be id and not paymentID

 {"id":"PAY-5T1130394T551090NLGRLACY"} ?

It took me 30 minutes to figure that out.

**Comment by bluepnume** [comment]
This is an example of an api, so it can return whatever you like.

Here's the front-end code which calls this api: https://developer.paypal.com/demo/checkout/#/pattern/server

```
                return paypal.request.post(CREATE_URL)
                    .then(function(res) {
                        return res.paymentID;
                    });
```

**Comment by gregjopa** [comment]
I think this issue can be closed. The old endpoint `/api/paypal/payment/create/` doesn't exist anymore. And the new endpoint `/api/paypal/order/create/` has been recently updated to return `res.send({ id: response })` to reduce confusion (https://github.com/paypal/paypal-checkout-demo/blob/master/src/app/server/routes.js#L23).
