### ISSUE TITLE
The Demo does not appear to work here or on developer.paypal.com

### ISSUE THREAD

**Issue by NikkiDreams** [paypal/paypal-checkout-demo#6]
This affects both this demo and the developer documentation examples in the PayPal Developer Portal.

Steps:
- Follow demo links in the public docs at developer.paypal.com
OR
- clone project
- replace clientIDs and secrets with working APP in sandbox
- Update callbacks in client portion of demo
- run via Docker per Readme
`± |master ?:1 ✗| → docker-compose up
Starting paypalcheckoutdemo_web_1
Attaching to paypalcheckoutdemo_web_1
web_1  | Server started at http://localhost:8002/demo/checkout`

The Button never renders. Basically nothing happens. It did work a few weeks ago. There are no errors in the browser or on the demo server. The only output in the client is the following:

`
util.js:64 XHR failed loading: POST "https://www.sandbox.paypal.com/webapps/hermes/api/logger".
09:50:56.072 util.js:64 XHR finished loading: POST "https://www.paypal.com/webapps/hermes/api/logger".`

![screen shot 2017-06-13 at 11 09 34 am](https://user-images.githubusercontent.com/1399736/27097423-0e1d7520-5029-11e7-9583-76de23d38670.png)

**Comment by gravescpa** [comment]
I am having the exact issue with the added bonus of the button appearing for about 3 seconds then disappearing

**Comment by bluepnume** [comment]
Hi -- sorry I missed this issue when it was originally supported. Can you:

- Confirm this issue happens even at https://developer.paypal.com/demo/checkout/ ? (even with the default code example?)
- Confirm which browser(s) you see the issue on?
- Paste your full integration code so I can try for myself

**Comment by bluepnume** [comment]
Are you still seeing this issue?
